### ISSUE TITLE
Default edit action

### ISSUE THREAD

**Issue by weblum** [weblum/PathEdit#2]
I have added unit tests. When you add an item with something like "+C:\something", the parser adds the item to the system hive. But when I construct a new EditItem for "C:\something", it is set as an item for the User hive. I believe these two item changes should refer to the same hive.

We need to discuss how this should work.

At the HEAD of the brillo branch, there is a unit test that illustrates this issue. It is currently failing, so we can see the issue clearly.

**Comment by Ol-Badger** [comment]
WOW!

 > On 4/20/2019 8:59:36 PM, William E Blum (notifications@github.com) wrote:
 > > I have added unit tests. When you add an item with something like 
"+C:\something", the parser adds the item to the system hive. But when I 
construct a new EditItem for "C:\something", it is set as an item for 
the User hive. I believe these two item changes should refer to the same 
hive.
 >
 > We need to discuss how this should work.
 >
 > At the HEAD of the brillo branch, there is a unit test that 
illustrates this issue. It is currently failing, so we can see the issue 
clearly.

**Comment by weblum** [comment]
On my own warrant I have found that the default result of a parse need not correspond to the default of construction of an EditItem. Hence, the unit test now takes that that into account and checks for non-default values of the EditItem. Case closed.
